// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Button.H>
extern void onBtnMsg(Fl_Button*, void*);
extern void onBtnQuit(Fl_Button*, void*);

class Gui {
public:
  Gui();
  Fl_Window *mainWnd;
  Fl_Pack *mainHBox;
  Fl_Button *btnMsg;
  Fl_Button *btnQuit;
  void show(int argc, char** argv);
  void close();
};
#endif
