// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "gui.h"

Gui::Gui() {
  { mainWnd = new Fl_Window(170, 70, "Template FLTK");
    mainWnd->user_data((void*)(this));
    { mainHBox = new Fl_Pack(-5, 0, 175, 75);
      { btnMsg = new Fl_Button(0, 10, 170, 25, "Message");
        btnMsg->callback((Fl_Callback*)onBtnMsg);
      } // Fl_Button* btnMsg
      { btnQuit = new Fl_Button(0, 40, 170, 25, "Quit");
        btnQuit->callback((Fl_Callback*)onBtnQuit);
      } // Fl_Button* btnQuit
      mainHBox->end();
    } // Fl_Pack* mainHBox
    mainWnd->end();
  } // Fl_Window* mainWnd
}

void Gui::show(int argc, char** argv) {
  mainWnd->show(argc,argv);
}

void Gui::close() {
  mainWnd->hide();
}
